<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 1,
                'data_type_id' => 1,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'data_type_id' => 1,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'data_type_id' => 1,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            3 => 
            array (
                'id' => 4,
                'data_type_id' => 1,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Senha',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            4 => 
            array (
                'id' => 5,
                'data_type_id' => 1,
                'field' => 'remember_token',
                'type' => 'hidden',
                'display_name' => 'Remember Token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 5,
            ),
            5 => 
            array (
                'id' => 6,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 6,
            ),
            6 => 
            array (
                'id' => 7,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 7,
            ),
            7 => 
            array (
                'id' => 8,
                'data_type_id' => 1,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 8,
            ),
            8 => 
            array (
                'id' => 9,
                'data_type_id' => 1,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Permissão',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":"0","taggable":"0"}',
                'order' => 10,
            ),
            9 => 
            array (
                'id' => 10,
                'data_type_id' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Permissões adicionais',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'order' => 11,
            ),
            10 => 
            array (
                'id' => 12,
                'data_type_id' => 1,
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 12,
            ),
            11 => 
            array (
                'id' => 13,
                'data_type_id' => 2,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            12 => 
            array (
                'id' => 14,
                'data_type_id' => 2,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            13 => 
            array (
                'id' => 15,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 3,
            ),
            14 => 
            array (
                'id' => 16,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            15 => 
            array (
                'id' => 17,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 1,
            ),
            16 => 
            array (
                'id' => 18,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 2,
            ),
            17 => 
            array (
                'id' => 19,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 3,
            ),
            18 => 
            array (
                'id' => 20,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '',
                'order' => 4,
            ),
            19 => 
            array (
                'id' => 21,
                'data_type_id' => 3,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '',
                'order' => 5,
            ),
            20 => 
            array (
                'id' => 22,
                'data_type_id' => 1,
                'field' => 'role_id',
                'type' => 'hidden',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 9,
            ),
            21 => 
            array (
                'id' => 57,
                'data_type_id' => 7,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            22 => 
            array (
                'id' => 58,
                'data_type_id' => 7,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            23 => 
            array (
                'id' => 59,
                'data_type_id' => 7,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            24 => 
            array (
                'id' => 60,
                'data_type_id' => 7,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            25 => 
            array (
                'id' => 77,
                'data_type_id' => 11,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            26 => 
            array (
                'id' => 78,
                'data_type_id' => 11,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            27 => 
            array (
                'id' => 79,
                'data_type_id' => 11,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            28 => 
            array (
                'id' => 80,
                'data_type_id' => 11,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            29 => 
            array (
                'id' => 81,
                'data_type_id' => 12,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            30 => 
            array (
                'id' => 82,
                'data_type_id' => 12,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"8"}}',
                'order' => 2,
            ),
            31 => 
            array (
                'id' => 83,
                'data_type_id' => 12,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            32 => 
            array (
                'id' => 84,
                'data_type_id' => 12,
                'field' => 'phone',
                'type' => 'text',
                'display_name' => 'Telefone',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"4"}}',
                'order' => 5,
            ),
            33 => 
            array (
                'id' => 85,
                'data_type_id' => 12,
                'field' => 'cpf',
                'type' => 'text',
                'display_name' => 'CPF',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 8,
            ),
            34 => 
            array (
                'id' => 86,
                'data_type_id' => 12,
                'field' => 'birth_day',
                'type' => 'date',
                'display_name' => 'Data de nascimento',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"format":"%H:%M:%S","display":{"width":"6"}}',
                'order' => 9,
            ),
            35 => 
            array (
                'id' => 87,
                'data_type_id' => 12,
                'field' => 'emergency_phone',
                'type' => 'text',
                'display_name' => 'Telefone para emergência',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"4"}}',
                'order' => 6,
            ),
            36 => 
            array (
                'id' => 88,
                'data_type_id' => 12,
                'field' => 'cep',
                'type' => 'text',
                'display_name' => 'Cep',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"4"}}',
                'order' => 11,
            ),
            37 => 
            array (
                'id' => 89,
                'data_type_id' => 12,
                'field' => 'neighborhood',
                'type' => 'text',
                'display_name' => 'Bairro',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"4"}}',
                'order' => 12,
            ),
            38 => 
            array (
                'id' => 90,
                'data_type_id' => 12,
                'field' => 'street',
                'type' => 'text',
                'display_name' => 'Endereço',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"10"}}',
                'order' => 13,
            ),
            39 => 
            array (
                'id' => 91,
                'data_type_id' => 12,
                'field' => 'number',
                'type' => 'text',
                'display_name' => 'Número',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"2"}}',
                'order' => 14,
            ),
            40 => 
            array (
                'id' => 92,
                'data_type_id' => 12,
                'field' => 'professional_id',
                'type' => 'hidden',
                'display_name' => 'Professional Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 15,
            ),
            41 => 
            array (
                'id' => 93,
                'data_type_id' => 12,
                'field' => 'sannyas',
                'type' => 'text',
                'display_name' => 'Sannyas',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"4"}}',
                'order' => 3,
            ),
            42 => 
            array (
                'id' => 95,
                'data_type_id' => 12,
                'field' => 'how_did_find_out_id',
                'type' => 'hidden',
                'display_name' => 'Como conheceu',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 17,
            ),
            43 => 
            array (
                'id' => 96,
                'data_type_id' => 12,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => '{"format":"%H:%M:%S"}',
                'order' => 18,
            ),
            44 => 
            array (
                'id' => 97,
                'data_type_id' => 12,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%H:%M:%S"}',
                'order' => 19,
            ),
            45 => 
            array (
                'id' => 99,
                'data_type_id' => 13,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            46 => 
            array (
                'id' => 100,
                'data_type_id' => 13,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            47 => 
            array (
                'id' => 101,
                'data_type_id' => 13,
                'field' => 'sannyas',
                'type' => 'text',
                'display_name' => 'Sannyas',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            48 => 
            array (
                'id' => 103,
                'data_type_id' => 13,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            49 => 
            array (
                'id' => 104,
                'data_type_id' => 13,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 6,
            ),
            50 => 
            array (
                'id' => 106,
                'data_type_id' => 12,
                'field' => 'customer_belongsto_professional_relationship',
                'type' => 'relationship',
                'display_name' => 'Profissional',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Professional","table":"professionals","type":"belongsTo","column":"professional_id","key":"id","label":"sannyas","pivot_table":"customer_participations","pivot":"0","taggable":"0"}',
                'order' => 22,
            ),
            51 => 
            array (
                'id' => 107,
                'data_type_id' => 13,
                'field' => 'professional_hasmany_customer_relationship',
                'type' => 'relationship',
                'display_name' => 'Clientes',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Customer","table":"customers","type":"hasMany","column":"professional_id","key":"id","label":"name","pivot_table":"customer_participations","pivot":"0","taggable":"0"}',
                'order' => 7,
            ),
            52 => 
            array (
                'id' => 108,
                'data_type_id' => 14,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            53 => 
            array (
                'id' => 109,
                'data_type_id' => 14,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            54 => 
            array (
                'id' => 110,
                'data_type_id' => 14,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            55 => 
            array (
                'id' => 111,
                'data_type_id' => 14,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            56 => 
            array (
                'id' => 113,
                'data_type_id' => 12,
                'field' => 'customer_belongsto_customer_type_relationship',
                'type' => 'relationship',
                'display_name' => 'Tipo de cliente',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\CustomerType","table":"customer_types","type":"belongsTo","column":"customer_type_id","key":"id","label":"name","pivot_table":"customer_participations","pivot":"0","taggable":"0"}',
                'order' => 23,
            ),
            57 => 
            array (
                'id' => 114,
                'data_type_id' => 12,
                'field' => 'customer_type_id',
                'type' => 'hidden',
                'display_name' => 'Customer Type Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 16,
            ),
            58 => 
            array (
                'id' => 115,
                'data_type_id' => 15,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            59 => 
            array (
                'id' => 116,
                'data_type_id' => 15,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            60 => 
            array (
                'id' => 117,
                'data_type_id' => 15,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            61 => 
            array (
                'id' => 118,
                'data_type_id' => 15,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            62 => 
            array (
                'id' => 119,
                'data_type_id' => 12,
                'field' => 'customer_belongsto_how_did_find_out_relationship',
                'type' => 'relationship',
                'display_name' => 'Como conheceu',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\HowDidFindOut","table":"how_did_find_outs","type":"belongsTo","column":"how_did_find_out_id","key":"id","label":"name","pivot_table":"customer_participations","pivot":"0","taggable":"0"}',
                'order' => 24,
            ),
            63 => 
            array (
                'id' => 120,
                'data_type_id' => 16,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            64 => 
            array (
                'id' => 121,
                'data_type_id' => 16,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            65 => 
            array (
                'id' => 122,
                'data_type_id' => 16,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            66 => 
            array (
                'id' => 123,
                'data_type_id' => 16,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            67 => 
            array (
                'id' => 124,
                'data_type_id' => 13,
                'field' => 'professional_belongsto_professional_type_relationship',
                'type' => 'relationship',
                'display_name' => 'Tipo de profissional',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\ProfessionalType","table":"professional_types","type":"belongsTo","column":"professional_type_id","key":"id","label":"name","pivot_table":"customer_participations","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            68 => 
            array (
                'id' => 125,
                'data_type_id' => 13,
                'field' => 'professional_type_id',
                'type' => 'hidden',
                'display_name' => 'Professional Type Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            69 => 
            array (
                'id' => 126,
                'data_type_id' => 14,
                'field' => 'customer_type_hasmany_customer_relationship',
                'type' => 'relationship',
                'display_name' => 'Clientes',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{"model":"App\\\\Customer","table":"customers","type":"hasMany","column":"customer_type_id","key":"id","label":"name","pivot_table":"customer_participations","pivot":"0","taggable":"0"}',
                'order' => 5,
            ),
            70 => 
            array (
                'id' => 127,
                'data_type_id' => 7,
                'field' => 'event_belongsto_event_classification_relationship',
                'type' => 'relationship',
                'display_name' => 'Classificação do evento',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\EventClassification","table":"event_classifications","type":"belongsTo","column":"event_classification_id","key":"id","label":"name","pivot_table":"customer_participations","pivot":"0","taggable":"0"}',
                'order' => 5,
            ),
            71 => 
            array (
                'id' => 128,
                'data_type_id' => 7,
                'field' => 'event_classification_id',
                'type' => 'hidden',
                'display_name' => 'Event Classification Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            72 => 
            array (
                'id' => 129,
                'data_type_id' => 11,
                'field' => 'event_classification_hasmany_event_relationship',
                'type' => 'relationship',
                'display_name' => 'Eventos',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{"model":"App\\\\Event","table":"events","type":"hasMany","column":"event_classification_id","key":"id","label":"name","pivot_table":"customer_participations","pivot":"0","taggable":"0"}',
                'order' => 5,
            ),
            73 => 
            array (
                'id' => 132,
                'data_type_id' => 22,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            74 => 
            array (
                'id' => 142,
                'data_type_id' => 22,
                'field' => 'event_id',
                'type' => 'hidden',
                'display_name' => 'Event Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            75 => 
            array (
                'id' => 152,
                'data_type_id' => 22,
                'field' => 'start',
                'type' => 'date',
                'display_name' => 'Início',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 6,
            ),
            76 => 
            array (
                'id' => 162,
                'data_type_id' => 22,
                'field' => 'end',
                'type' => 'date',
                'display_name' => 'Término',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"6"}}',
                'order' => 7,
            ),
            77 => 
            array (
                'id' => 172,
                'data_type_id' => 22,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 8,
            ),
            78 => 
            array (
                'id' => 182,
                'data_type_id' => 22,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 9,
            ),
            79 => 
            array (
                'id' => 191,
                'data_type_id' => 22,
                'field' => 'participation_belongsto_event_relationship',
                'type' => 'relationship',
                'display_name' => 'Evento',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Event","table":"events","type":"belongsTo","column":"event_id","key":"id","label":"name","pivot_table":"customer_participations","pivot":"0","taggable":"0"}',
                'order' => 3,
            ),
            80 => 
            array (
                'id' => 202,
                'data_type_id' => 22,
                'field' => 'participation_belongstomany_customer_relationship',
                'type' => 'relationship',
                'display_name' => 'Clientes',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Customer","table":"customers","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"customer_participations","pivot":"1","taggable":"0"}',
                'order' => 4,
            ),
            81 => 
            array (
                'id' => 211,
                'data_type_id' => 22,
                'field' => 'participation_belongstomany_professional_relationship',
                'type' => 'relationship',
                'display_name' => 'Profissionais',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Professional","table":"professionals","type":"belongsToMany","column":"id","key":"id","label":"sannyas","pivot_table":"professional_participations","pivot":"1","taggable":"0"}',
                'order' => 5,
            ),
            82 => 
            array (
                'id' => 221,
                'data_type_id' => 12,
                'field' => 'marital_status',
                'type' => 'select_dropdown',
                'display_name' => 'Estado Civil',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
            'details' => '{"default":"0","options":{"0":"Solteiro(a)","1":"Casado(a)"},"display":{"width":"6"}}',
                'order' => 20,
            ),
            83 => 
            array (
                'id' => 231,
                'data_type_id' => 12,
                'field' => 'sexo',
                'type' => 'select_dropdown',
                'display_name' => 'Sexo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"options":{"0":"Masculino","1":"Feminino"},"display":{"width":"6"}}',
                'order' => 21,
            ),
            84 => 
            array (
                'id' => 241,
                'data_type_id' => 12,
                'field' => 'community',
                'type' => 'checkbox',
                'display_name' => 'Community',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"Sim","off":"Não","display":{"width":"6"}}',
                'order' => 25,
            ),
            85 => 
            array (
                'id' => 251,
                'data_type_id' => 12,
                'field' => 'comments',
                'type' => 'text_area',
                'display_name' => 'Observações',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 27,
            ),
            86 => 
            array (
                'id' => 261,
                'data_type_id' => 12,
                'field' => 'secondary_phone',
                'type' => 'text',
                'display_name' => 'Telefone Secundário',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"4"}}',
                'order' => 7,
            ),
            87 => 
            array (
                'id' => 271,
                'data_type_id' => 12,
                'field' => 'friends',
                'type' => 'checkbox',
                'display_name' => 'Amigos',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"Sim","off":"Não","display":{"width":"6"}}',
                'order' => 26,
            ),
            88 => 
            array (
                'id' => 291,
                'data_type_id' => 12,
                'field' => 'country',
                'type' => 'select_dropdown',
                'display_name' => 'País',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"4"}}',
                'order' => 10,
            ),
            89 => 
            array (
                'id' => 301,
                'data_type_id' => 31,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            90 => 
            array (
                'id' => 311,
                'data_type_id' => 31,
                'field' => 'file',
                'type' => 'image',
                'display_name' => 'Ficha',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"display":{"width":"10"}}',
                'order' => 2,
            ),
            91 => 
            array (
                'id' => 321,
                'data_type_id' => 31,
                'field' => 'active',
                'type' => 'checkbox',
                'display_name' => 'Ativo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"on":"Sim","off":"Não","display":{"width":"2"}}',
                'order' => 3,
            ),
            92 => 
            array (
                'id' => 331,
                'data_type_id' => 31,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nome',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            93 => 
            array (
                'id' => 341,
                'data_type_id' => 31,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Criado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%H:%M:%S"}',
                'order' => 5,
            ),
            94 => 
            array (
                'id' => 351,
                'data_type_id' => 31,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Editado em',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"format":"%H:%M:%S"}',
                'order' => 6,
            ),
            95 => 
            array (
                'id' => 361,
                'data_type_id' => 31,
                'field' => 'file_belongsto_customer_relationship',
                'type' => 'relationship',
                'display_name' => 'Cliente',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Customer","table":"customers","type":"belongsTo","column":"customer_id","key":"id","label":"name","pivot_table":"customer_participations","pivot":"0","taggable":"0"}',
                'order' => 7,
            ),
            96 => 
            array (
                'id' => 371,
                'data_type_id' => 31,
                'field' => 'customer_id',
                'type' => 'hidden',
                'display_name' => 'Customer Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 7,
            ),
        ));
        
        
    }
}